CREATE TABLE  LOGIN 
   (	
		LOGIN_ID NUMBER(10,0) NOT NULL, 
		USER_NAME VARCHAR2(255 CHAR), 
		PASSWORD VARCHAR2(255 CHAR),
		PRIMARY KEY (LOGIN_ID) 
   );
   
 CREATE SEQUENCE LOGIN_ID_SEQ
  START WITH 1;